# Generated by Django 6.0.3 on 2026-05-14 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('strategy_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('FUTURES', 'Futures')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_return', models.FloatField()),
                ('cagr', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('sortino_ratio', models.FloatField()),
                ('drawdown', models.FloatField()),
                ('total_trade', models.PositiveBigIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('average_win', models.FloatField(default=0.0)),
                ('average_loss', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_symbol', models.CharField(max_length=10)),
                ('contract_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pct', models.FloatField(default=0.0)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='base.backtest')),
            ],
        ),
        migrations.CreateModel(
            name='EquityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('cash', models.DecimalField(decimal_places=8, max_digits=20)),
                ('holdings_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pct', models.FloatField(default=0.0)),
                ('drawdown', models.FloatField(default=0.0)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_point', to='base.backtest')),
            ],
        ),
        migrations.AddField(
            model_name='backtest',
            name='futures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.futurescontract'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stock'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_holdings', models.DecimalField(decimal_places=2, default=100000.0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('High_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_price_history', to='base.futurescontract')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contracts', 'date'), name='unique_contract_date')],
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_price_history', to='base.stock')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date')],
            },
        ),
    ]
