# Generated by Django 6.0.3 on 2026-05-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='futures',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='backtesttrade',
            name='backtest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('strategy_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('FUTURES', 'Futures')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('futures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.futurescontract')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioEquityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('holdings_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realised_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealised_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_exposure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_exposure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_exposure_leverage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_record', to='base.backtestrun')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioFillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fill_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('previous_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realised_pnl_day', models.DecimalField(decimal_places=4, max_digits=20)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_record', to='base.backtestrun')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPositionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unrealised_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_record', to='base.backtestrun')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stock')),
            ],
            options={
                'ordering': ['date', 'ticker'],
            },
        ),
        migrations.DeleteModel(
            name='EquityPoint',
        ),
        migrations.DeleteModel(
            name='Backtest',
        ),
        migrations.DeleteModel(
            name='BacktestTrade',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddConstraint(
            model_name='portfolioequityrecord',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'date'), name='unique_equity_record'),
        ),
        migrations.AddConstraint(
            model_name='portfoliopositionrecord',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'date', 'ticker'), name='Unique_positions'),
        ),
    ]
