# Generated by Django 6.0.3 on 2026-07-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperorder',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forex_order', to='base.forexpair'),
        ),
        migrations.AlterField(
            model_name='paperorder',
            name='futures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futures_order', to='base.futurescontract'),
        ),
        migrations.AlterField(
            model_name='paperorder',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_order', to='base.stock'),
        ),
        migrations.AlterField(
            model_name='paperpositions',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forex_positions', to='base.forexpair'),
        ),
        migrations.AlterField(
            model_name='paperpositions',
            name='futures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futures_positions', to='base.futurescontract'),
        ),
        migrations.AlterField(
            model_name='paperpositions',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to='base.stock'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='base.paperorder'),
        ),
    ]
