# Generated by Django 6.0.3 on 2026-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_backtest_futures_remove_backtest_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='fixed_quantity',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=15),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='tickers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
