# Generated by Django 6.0.3 on 2026-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_backtestrun_completed_at_backtestrun_fixed_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtestrun',
            old_name='starting_capital',
            new_name='initial_capital',
        ),
        migrations.RenameField(
            model_name='backtestrun',
            old_name='name',
            new_name='run_name',
        ),
    ]
