# Generated by Django 6.0.5 on 2026-06-21 06:20

import django.core.serializers.json
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_starting_capital_backtestrun_initial_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unrealised_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousFuturesPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('active_contracts', models.BigIntegerField(default=0)),
                ('adjustment_val', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=20)),
                ('is_rolled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['series', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousFuturesSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_symbol', models.CharField(max_length=20)),
                ('contract_index', models.PositiveSmallIntegerField(default=1)),
                ('rollover_rule', models.CharField(choices=[('DAYS_BEFORE_EXPIRY', 'Days Before Expiry'), ('VOLUME', 'Volume'), ('ACTIVE_CONTRACTS', 'Active Contracts'), ('MANUAL', 'Manual')], default='DAYS_BEFORE_EXPIRY', max_length=30)),
                ('roll_days', models.PositiveSmallIntegerField(default=5)),
                ('adjustment_method', models.CharField(choices=[('NONE', 'No adjustment'), ('BACK_ADJUSTED', 'Back adjusted'), ('RATIO_ADJUSTED', 'Ratio adjusted')], default='BACK_ADJUSTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('pip_value', models.FloatField(default=0.0001)),
                ('lot_size', models.IntegerField(default=100000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FuturesRollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['series', 'roll_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='futurescontract',
            options={'ordering': ['root_symbol', 'expiry_date']},
        ),
        migrations.AlterModelOptions(
            name='futurespricehistory',
            options={'ordering': ['contract', 'date']},
        ),
        migrations.RemoveConstraint(
            model_name='futurespricehistory',
            name='unique_contract_date',
        ),
        migrations.RenameField(
            model_name='futurespricehistory',
            old_name='contracts',
            new_name='contract',
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='slippage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_params',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Strategy specific parameters'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='exchange',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='tick_multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='tick_size',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.01'), max_digits=20),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='active_contracts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('FUTURES', 'Futures'), ('FOREX', 'Forex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='futurespricehistory',
            name='close_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='futurespricehistory',
            name='low_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='futurespricehistory',
            name='open_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliopositionrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliopositionrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['root_symbol', 'expiry_date'], name='base_future_root_sy_f6d31f_idx'),
        ),
        migrations.AddIndex(
            model_name='futurespricehistory',
            index=models.Index(fields=['contract', 'date'], name='base_future_contrac_a4428a_idx'),
        ),
        migrations.AddIndex(
            model_name='futurespricehistory',
            index=models.Index(fields=['date'], name='base_future_date_1fca4f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpricehistory',
            index=models.Index(fields=['stock', '-date'], name='Unique_stock_price_date'),
        ),
        migrations.AddConstraint(
            model_name='futurespricehistory',
            constraint=models.UniqueConstraint(fields=('contract', 'date'), name='unique_contract_date'),
        ),
        migrations.AddField(
            model_name='benchmarkrecord',
            name='backtest_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_record', to='base.backtestrun'),
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='source_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_contract', to='base.futurescontract'),
        ),
        migrations.AddConstraint(
            model_name='continuousfuturesseries',
            constraint=models.UniqueConstraint(fields=('contract_symbol', 'contract_index', 'rollover_rule', 'roll_days', 'adjustment_method'), name='unique_continuous_futures_series'),
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='base.continuousfuturesseries'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.forexpair'),
        ),
        migrations.AddField(
            model_name='portfoliopositionrecord',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.forexpair'),
        ),
        migrations.AddField(
            model_name='forexpricehistory',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_price_history', to='base.forexpair'),
        ),
        migrations.AddField(
            model_name='futuresrollevent',
            name='from_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_from', to='base.futurescontract'),
        ),
        migrations.AddField(
            model_name='futuresrollevent',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_events', to='base.continuousfuturesseries'),
        ),
        migrations.AddField(
            model_name='futuresrollevent',
            name='to_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_to', to='base.futurescontract'),
        ),
        migrations.RemoveField(
            model_name='futurespricehistory',
            name='High_price',
        ),
        migrations.AddConstraint(
            model_name='benchmarkrecord',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'date'), name='unique_benchmark_record'),
        ),
        migrations.AddConstraint(
            model_name='continuousfuturespricehistory',
            constraint=models.UniqueConstraint(fields=('series', 'date'), name='Unique_continuous_series_date'),
        ),
        migrations.AddIndex(
            model_name='forexpricehistory',
            index=models.Index(fields=['pair', 'timestamp'], name='forex_pair_timestamp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forexpricehistory',
            unique_together={('pair', 'timestamp')},
        ),
        migrations.AddConstraint(
            model_name='futuresrollevent',
            constraint=models.UniqueConstraint(fields=('series', 'roll_date'), name='unique_futures_roll_event'),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='high_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
