# Generated by Django 6.0.3 on 2026-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_starting_capital_backtestrun_initial_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfolioequityrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfoliofillrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliopositionrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliopositionrecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
