# Generated by Django 6.0.3 on 2026-06-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_backtestrun_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('pip_value', models.FloatField(default=0.0001)),
                ('lot_size', models.IntegerField(default=100000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('FUTURES', 'Futures'), ('FOREX', 'Forex')], max_length=10),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.forexpair'),
        ),
        migrations.CreateModel(
            name='BenchmarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unrealised_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_record', to='base.backtestrun')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('backtest_run', 'date'), name='unique_benchmark_record')],
            },
        ),
        migrations.CreateModel(
            name='ForexPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_price_history', to='base.forexpair')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['pair', 'timestamp'], name='forex_pair_timestamp_idx')],
                'unique_together': {('pair', 'timestamp')},
            },
        ),
    ]
