# Generated by Django 6.0.5 on 2026-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_benchmarkrecord_continuousfuturespricehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='risk_free_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
