# Generated by Django 6.0.3 on 2026-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_forexpair_alter_backtestrun_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexpricehistory',
            name='volume',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
