# Generated by Django 6.0.5 on 2026-06-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_paperaccount_paperorder_paperpositions_papertrade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperorder',
            old_name='order_type',
            new_name='type',
        ),
    ]
