# Generated by Django 6.0.3 on 2026-06-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_forexpricehistory_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forexpricehistory',
            old_name='close',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='forexpricehistory',
            old_name='high',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='forexpricehistory',
            old_name='low',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='forexpricehistory',
            old_name='open',
            new_name='open_price',
        ),
    ]
