# Generated by Django 6.0.3 on 2026-06-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_close_forexpricehistory_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopositionrecord',
            name='forex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.forexpair'),
        ),
    ]
