# Generated by Django 6.0.5 on 2026-07-08 13:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_order_type_paperorder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuousfuturespricehistory',
            old_name='is_rolled',
            new_name='is_roll',
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='roll_from_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roll_from_contract', to='base.futurescontract'),
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='roll_from_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='roll_to_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roll_to_contract', to='base.futurescontract'),
        ),
        migrations.AddField(
            model_name='continuousfuturespricehistory',
            name='roll_to_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliofillrecord',
            name='source_contract_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopositionrecord',
            name='future',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.futurescontract'),
        ),
        migrations.AddField(
            model_name='portfoliopositionrecord',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
