# Generated by Django 6.0.3 on 2026-06-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_continuousfuturespricehistory_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='continuousfuturesseries',
            name='unique_continuous_futures_series',
        ),
        migrations.AddConstraint(
            model_name='continuousfuturesseries',
            constraint=models.UniqueConstraint(fields=('contract_symbol', 'contract_index', 'rollover_rule', 'roll_days', 'adjustment_method'), name='unique_continuous_futures_series'),
        ),
    ]
