# Generated by Django 6.0.5 on 2026-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_continuousfuturespricehistory_roll_from_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousfuturesseries',
            name='adjustment_method',
            field=models.CharField(blank=True, choices=[('NONE', 'No adjustment'), ('BACK_ADJUSTED', 'Back adjusted'), ('RATIO_ADJUSTED', 'Ratio adjusted')], default='BACK_ADJUSTED', max_length=30, null=True),
        ),
    ]
