# Generated by Django 6.0.5 on 2026-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_continuousfuturesseries_adjustment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='risk_free_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='slippage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='strength',
            field=models.IntegerField(),
        ),
    ]
