# Generated by Django 6.0.3 on 2026-06-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_continuousfuturesseries_unique_continuous_futures_series_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurespricehistory',
            old_name='High_price',
            new_name='high_price',
        ),
    ]
