# Generated by Django 6.0.3 on 2026-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_high_price_futurespricehistory_high_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousfuturesseries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='stockpricehistory',
            index=models.Index(fields=['stock', '-date'], name='Unique_stock_price_date'),
        ),
    ]
