# Generated by Django 6.0.5 on 2026-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_backtestrun_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='commission',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='risk_free_rate',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='slippage',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='strength',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
    ]
