# Generated by Django 6.0.3 on 2026-06-27 04:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_continuousfuturesseries_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paper Account', max_length=10)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LMT', 'Limit')], default='MARKET', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.paperaccount')),
                ('forex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forex_order', to='base.forexpair')),
                ('futures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='futures_order', to='base.futurescontract')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_order', to='base.stock')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('accum_borrowed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('realised_pnl', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='base.paperaccount')),
                ('forex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forex_positions', to='base.forexpair')),
                ('futures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='futures_positions', to='base.futurescontract')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_positions', to='base.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fulfilled_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('closed_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('opened_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('realised_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cash_change', models.DecimalField(decimal_places=4, max_digits=20)),
                ('executed_at', models.DateField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trade', to='base.paperorder')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='Unique_paper_account'),
        ),
        migrations.AddIndex(
            model_name='paperorder',
            index=models.Index(fields=['account', 'status', 'submitted_at'], name='base_papero_account_68f2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='paperpositions',
            index=models.Index(fields=['account', 'stock', 'forex', 'futures'], name='paper_positions'),
        ),
    ]
