# Generated by Django 6.0.3 on 2026-06-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_paperaccount_paperorder_paperpositions_papertrade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperorder',
            old_name='order_type',
            new_name='type',
        ),
    ]
