# Generated by Django 5.2.3 on 2026-07-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_is_rolled_continuousfuturespricehistory_is_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_from_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_to_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
