# Generated by Django 5.2.3 on 2026-07-06 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_continuousfuturespricehistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_from_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_to_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
    ]
