# Generated by Django 5.2.3 on 2026-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_continuousfuturespricehistory_roll_from_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliofillrecord',
            name='source_contract_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
