# Generated by Django 5.2.3 on 2026-07-07 07:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_portfoliofillrecord_source_contract_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopositionrecord',
            name='mutliplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=20),
        ),
    ]
