# Generated by Django 5.2.3 on 2026-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_mutliplier_portfoliopositionrecord_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_from_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='continuousfuturespricehistory',
            name='roll_to_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
