from django.test import TestCase
import factory
from datetime import datetime
from base.engine.data_loader import DataLoader
from base.models import StockPriceHistory, Stock

# Using factoryboy to make it easier to generate Stock and SPH
class StockFactory(factory.django.DjangoModelFactory):
    '''
    Used for fast and random generation of Stock models
    '''
    class Meta:
        model = Stock
        django_get_or_create = ("ticker",)
    ticker = factory.Sequence(lambda n: f"Ticker_{n}")
    name = factory.Sequence(lambda n: f"name_{n}")
    industry = "Electronics"
    is_active = True

class StockPriceHistoryFactory(factory.django.DjangoModelFactory):
    '''
    Used for fast and random generation of StockPriceHistory models
    '''
    class Meta:
        model = StockPriceHistory
    stock = factory.SubFactory(StockFactory)
    date = datetime.fromisoformat("2025-01-01")
    open_price = 10
    high_price =12
    low_price = 8
    volume = 1000
    close_price = 11


print(f"This is a Stock generated by Stock Factory = {StockFactory()}")
print(f"This is a SPH generated by SPH Factory = {StockPriceHistoryFactory()}")

# class DataLoaderTest(TestCase):
#     ''' 
#     A class for testing a data loader
#     '''
#     def setup(self):
#         Stock.objects.create(ticker="AAPL",
#                              name="AAPL",
#                              industry="Electronics",
#                              is_active=True)
#         StockPriceHistory.objects.create()
